In [8]:
import pandas as pd

df_all= pd.read_excel("C:/Users/USER/Documents/카카오톡 받은 파일/2023년 유초중등 학교별 학년별 학생수 학급수 입학 졸업 교원 직원 면적_240319.xlsx", sheet_name='학교별 주요통계', header=14, usecols='A:ER')
df_comb= pd.read_excel('C:/Users/USER/Documents/카카오톡 받은 파일/통합학교모음.xlsx', usecols='A:EU')

In [33]:
df_comb

,조사기준일,시도,행정구,교육\n(지원)청,학교급,고등학교\n유형,학교세부유형,학교운영상특례,학교명,학교명(영문명),...,국외_대학_남,국외_대학_여,일반\n교실,교과\n교실,특별\n교실,수준별교실,기타\n교실,교지면적,학생\n1인당\n교지면적,구분
0,20230401,강원,삼척시,강원,고등학교,일반고등학교,일반고등학교,해당없음,가곡고등학교,Gagok High School,...,0,0,6,0,5,0,0,11424,3808.0,34
1,20230401,강원,삼척시,강원,고등학교,일반고등학교,일반고등학교,해당없음,삼일고등학교,Samil High School,...,0,0,9,0,2,1,0,19598,89.5,28
2,20230401,강원,삼척시,삼척,중학교,NaN,일반중학교,해당없음,가곡중학교,Gagok Middle School,...,0,0,0,0,0,0,0,0,0.0,34
3,20230401,강원,삼척시,삼척,중학교,NaN,일반중학교,해당없음,삼일중학교,Samil Middle School,...,0,0,12,2,6,0,4,0,0.0,28
4,20230401,강원,영월군,강원,고등학교,일반고등학교,일반고등학교,해당없음,영월고등학교,Yeongwol High School,...,0,0,12,2,3,0,0,26888,99.2,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,20230401,경기,시흥시,시흥,각종학교,NaN,각종학교(초등+중학+고교),대안학교,군서미래국제학교,Gunseo Global School,...,0,0,6,15,5,0,1,12404,34.6,134
252,20230401,경기,성남시,성남,초등학교,NaN,초등학교,해당없음,판교대장초등학교,Pangyo-Daejang Elementary School,...,0,0,58,5,17,0,0,23375,24.2,135
253,20230401,경기,성남시,성남,중학교,NaN,일반중학교,해당없음,판교대장중학교,Pangyodaejang Middle School,...,0,0,0,0,0,0,0,0,0.0,135
254,20230401,경기,안성시,안성,중학교,NaN,일반중학교,해당없음,죽산중학교,Juksan Middle School,...,0,0,7,2,6,0,0,19661,162.5,136
255,20230401,경기,안성시,경기,고등학교,일반고등학교,종합고등학교,일반고(직업계열학과),죽산고등학교,Juksan High School,...,0,0,10,2,7,0,1,14605,110.6,136

In [24]:
df_all['학교급'].unique()

array(['고등학교', '특수학교', '고등기술학교', '각종학교', '방송통신고등학교', '유치원', '초등학교', '중학교',
       '방송통신중학교', '고등공민학교'], dtype=object)

In [40]:
df_incheon_elementary= df_all[(df_all['시도']=='인천') & (df_all['학교급']=='초등학교')]
df_incheon_middle= df_all[(df_all['시도']=='인천') & (df_all['학교급']=='중학교')]
df_incheon_high= df_all[(df_all['시도']=='인천') & (df_all['학교급']=='고등학교')]

In [ ]:
df_incheon_elementary

In [34]:
comb_list= df_comb['학교명'].to_list()

In [41]:
df_final_elmentary= df_incheon_elementary[~df_incheon_elementary['학교명'].isin(comb_list)]
df_final_middle= df_incheon_middle[~df_incheon_middle['학교명'].isin(comb_list)]
df_final_high= df_incheon_high[~df_incheon_high['학교명'].isin(comb_list)]

In [45]:
df_final_elmentary.to_csv('incheon_elementary.csv')
df_final_middle.to_csv('incheon_middle.csv')
df_final_high.to_csv('incheon_high.csv')

'c:\\Users\\USER\\AppData\\Local\\Programs\\Microsoft VS Code'